Remove node import from site.pp
Switching to directory environments meant that the main puppet manifest
switched from $env/manifests/site.pp to the entire $env/manifests/
directory. Each manifest in this directory is automatically loaded, so
importing nodes.pp from within site.pp created an import loop:

Error: Could not parse for environment production: Import loop detected
for [...]/manifests/nodes.pp at [...]/manifests/site.pp:30

Some additional info here:
http://docs.puppetlabs.com/puppet/latest/reference/dirs_manifest.html