ocf: move matplotlib, switch backend if headless
This helps to avoid errors like:

    Traceback (most recent call last):
      File "/opt/stats/labstats/labstats/stats/utilization-graph.py", line 88, in <module>
        generate_image(profiles, hosts, start, end, args.dest)
      File "/opt/stats/labstats/labstats/stats/utilization-graph.py", line 53, in generate_image
        plt.figure(figsize=(10,6))
      File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 435, in figure
        **kwargs)
      File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
        return new_figure_manager_given_figure(num, figure)
      File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
        window = Tk.Tk()
      File "/usr/lib/python3.4/tkinter/__init__.py", line 1854, in __init__
        self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
    _tkinter.TclError: no display name and no $DISPLAY environment variable

Alternatively, we could go modify all of our code. But you have to do:

    import matplotlib as mpl
    mpl.use('Agg')
    import matplotlib.pyplot as plt

...which looks horrible and probably causes linters to complain.